nameOverride: ""
fullnameOverride: "credential-showcase"

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: openshift-default
    route.openshift.io/termination: edge
  hosts:
    - host: credential-showcase-api-dev.apps.silver.devops.gov.bc.ca
      paths:
        - path: /
          pathType: Prefix
          service: api-server
    - host: credential-showcase-traction-adapter-dev.apps.silver.devops.gov.bc.ca
      paths:
        - path: /
          pathType: Prefix
          service: traction-adapter
  tls: []

api_server:
  name: credential-showcase-api-server
  image:
    repository: public.ecr.aws/k8o4d9r5/bcshowcase/credential-showcase-api-server
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: "latest"
  replicaCount: 1
  labelOverride: ""
  port: 3000
  path: /
  env:
    APP_NAME: credential-showcase-api
    LOG_LEVEL: debug
    DB_HOST: credential-showcase-postgresql
    DB_PORT: "5432"
    DB_NAME: showcase-db
    DB_USERNAME: showcase-user
    CORS_DISABLED: true
    ALLOW_ORIGINS: "*"
    ALLOW_METHODS: "GET, POST, PUT, DELETE, OPTIONS"
    ALLOW_HEADERS: "Content-Type, Authorization"
    ALLOW_CREDENTIALS: "true"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  service:
    type: ClusterIP
    port: 3000
  affinity: {}
  nodeSelector: {}
  tolerations: []
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector: {}
      podSelector: {}
  openshift:
    route:
      enabled: false
      path: "/"
      targetPort: http
      timeout: 2m
      host: ""
      tls:
        enabled: true
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      wildcardPolicy: None
  enabled: true
  serviceAccount:
    create: false
    name: ""
    annotations: {}
    automountServiceAccountToken: true
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300

traction_adapter:
  name: credential-showcase-traction-adapter
  image:
    repository: public.ecr.aws/k8o4d9r5/bcshowcase/credential-showcase-traction-adapter
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: "latest"
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300
  labelOverride: ""
  port: 3000
  path: /traction
  env:
    APP_NAME: credential-showcase-traction-adapter
    LOG_LEVEL: debug
    NODE_PORT: 3000
    RABBITMQ_HOST: rabbitmq
    RABBITMQ_PORT: 5672
    RABBITMQ_USER: guest
    RABBITMQ_VHOST: /
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  service:
    type: ClusterIP
    port: 3000
  affinity: {}
  nodeSelector: {}
  tolerations: []
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector: {}
      podSelector: {}
  openshift:
    route:
      enabled: false
      path: "/"
      targetPort: http
      timeout: 2m
      host: ""
      tls:
        enabled: true
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      wildcardPolicy: None
  enabled: true
  serviceAccount:
    create: false
    annotations: {}
    automountServiceAccountToken: true
    name: ""

postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    username: "showcase-user"
    database: "showcase-db"
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "password"
  primary:
    service:
      ports:
        postgresql: 5432
    persistence:
      enabled: true
      size: 1Gi
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
  networkPolicy:
    enabled: true

rabbitmq:
  enabled: true
  auth:
    username: "guest"
    password: ""
    secretKeys:
      passwordKey: "rabbitmq-password"
      erlangCookieKey: "rabbitmq-erlang-cookie"
  plugins: "rabbitmq_management"
  extraConfiguration: |
    management.listener.port = 15672
    management.listener.ssl = false
  service:
    ports:
      amqp: 5672
      management: 15672
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  replicaCount: 1
  pdb:
    create: true
    minAvailable: 1
  networkPolicy:
    enabled: true

global:
  namespaceOverride: ""