{{- if .Values.showcase.networkPolicy.enabled }}
---
# API ingress from frontend only.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "showcase.fullname" . }}-server-ingress
  namespace: {{ include "showcase.namespace" . | quote }}
  labels: {{- include "showcase.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  podSelector:
    matchLabels:
      {{- include "showcase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: {{ .Values.showcase.server.containerPort }}
      from:
        - podSelector:
            matchLabels:
              {{- include "showcase.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: frontend
---
# API egress: Mongo (if enabled), DNS, HTTPS.
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "showcase.fullname" . }}-server-egress
  namespace: {{ include "showcase.namespace" . | quote }}
  labels: {{- include "showcase.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  podSelector:
    matchLabels:
      {{- include "showcase.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  policyTypes:
    - Egress
  egress:
    - {}
{{- end }}
