apiVersion: v1
kind: Service
metadata:
  name: {{ include "showcase.server.fullname" . }}
  namespace: {{ include "showcase.namespace" . | quote }}
  labels: {{- include "showcase.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    {{- include "showcase.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - name: http
      port: 5000
      targetPort: http
