name: Setup NodeJS
description: Setup NodeJS with caching
author: 'timo@animo.id'

inputs:
  node-version:
    description: Node version to use
    required: true

runs:
  using: composite
  steps:
    - name: Setup node v${{ inputs.node-version }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: yarn
        cache-dependency-path: yarn.lock

branding:
  icon: scissors
  color: purple
