name: Setup NodeJS
description: Setup NodeJS with Corepack and Yarn caching
author: 'timo@animo.id'

inputs:
  node-version:
    description: Node version to use
    required: true

runs:
  using: composite
  steps:
    - name: Setup node v${{ inputs.node-version }}
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
      with:
        node-version: ${{ inputs.node-version }}
    - name: Enable Corepack
      shell: bash
      run: |
        corepack enable
        corepack install --global yarn@4.18.0
    - name: Verify Yarn version
      shell: bash
      run: test "$(yarn --version)" = "4.18.0"
    - name: Get Yarn cache directory
      id: yarn-cache-dir
      shell: bash
      run: echo "dir=$(yarn config get cacheFolder)" >> "$GITHUB_OUTPUT"
    - name: Cache Yarn dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache-dir.outputs.dir }}
        key: yarn-${{ runner.os }}-node-${{ inputs.node-version }}-yarn-4.18.0-${{ hashFiles('yarn.lock') }}

branding:
  icon: scissors
  color: purple
