version: "3.9"
services:
  frontend:
    image: bc-wallet-demo-web
    build: 
      context: ./
      dockerfile: ./apps/bc-wallet-demo-web/Dockerfile
    volumes:
      - type: bind
        source: ./apps/bc-wallet-demo-web/Caddyfile
        target: /etc/caddy/Caddyfile
    ports:
      - "3000:3000"
    depends_on: 
      - backend
    env_file:
      - ./apps/bc-wallet-demo-web/.env
  backend:
    image: bc-wallet-demo-server
    build: 
      context: ./
      dockerfile: ./apps/bc-wallet-demo-server/Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./apps/bc-wallet-demo-server/.env
  dev:
    image: bc-wallet-demo-dev
    build:
      context: ./
      dockerfile: ./dev.dockerfile
    ports:
      - "3000:3000"
      - "5000:5000"
    volumes:
      - ./:/app
  