{{- if and .Values.traction_adapter.enabled .Values.traction_adapter.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-{{ .Values.traction_adapter.name }}-allow-external
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/component: adapter
    app.kubernetes.io/part-of: credential-showcase
    {{- include "credential-showcase.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.traction_adapter.name }}
  ingress:
  - {}  # Allow all ingress traffic
---
# Network policy for Traction Adapter to RabbitMQ
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-rabbitmq-allow-adapter
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/component: messagebroker
    app.kubernetes.io/part-of: credential-showcase
    {{- include "credential-showcase.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-{{ .Values.traction_adapter.name }}
    ports:
    - protocol: TCP
      port: {{ .Values.rabbitmq.service.ports.amqp }}
{{- end }}