{{- if .Values.traction_adapter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.traction_adapter.name }}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/component: adapter
    app.kubernetes.io/part-of: credential-showcase
    {{- include "credential-showcase.labels" . | nindent 4 }}
spec:
  type: {{ .Values.traction_adapter.service.type }}
  ports:
    - port: {{ .Values.traction_adapter.service.port }}
      targetPort: {{ .Values.traction_adapter.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-{{ .Values.traction_adapter.name }}
{{- end }}