{{- if .Values.traction_adapter.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.traction_adapter.name }}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/component: adapter
    app.kubernetes.io/part-of: bc-wallet
    {{- include "bc-wallet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.traction_adapter.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.traction_adapter.name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.traction_adapter.name }}
        app.kubernetes.io/component: adapter
        app.kubernetes.io/part-of: bc-wallet
        {{- include "bc-wallet.labels" . | nindent 8 }}
      {{- with .Values.traction_adapter.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.traction_adapter.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.traction_adapter.name }}
        image: "{{ .Values.traction_adapter.image.repository }}:{{ .Values.traction_adapter.image.tag }}"
        imagePullPolicy: {{ .Values.traction_adapter.image.pullPolicy }}
        {{- with .Values.traction_adapter.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.traction_adapter.port }}
          name: http
        env:
          - name: AMQ_HOST
            value: {{ include "bc-wallet.rabbitmq.host" . | quote }}
          - name: AMQ_PORT
            value: {{ include "bc-wallet.rabbitmq.port" . | quote }}
          - name: AMQ_TRANSPORT
            value: tcp
          - name: AMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ include "bc-wallet.rabbitmq.secretName" . }}
                key: {{ include "bc-wallet.rabbitmq.passwordKey" . }}
          - name: AMQ_USERNAME
            value: {{ .Values.rabbitmq.auth.username | quote }}
          {{- range $key, $value := .Values.traction_adapter.env }}
          {{- if and (ne $key "AMQ_HOST") (ne $key "AMQ_PORT") (ne $key "AMQ_TRANSPORT") (ne $key "AMQ_PASSWORD") (ne $key "AMQ_USERNAME") (kindIs "map" $value) }}
          - name: {{ $key }}
            valueFrom:
              {{- toYaml $value | nindent 14 }}
          {{- else if and (ne $key "AMQ_HOST") (ne $key "AMQ_PORT") (ne $key "AMQ_TRANSPORT") (ne $key "AMQ_PASSWORD") (ne $key "AMQ_USERNAME") }}
          - name: {{ $key }}
            value: {{ $value | quote }}
          {{- end }}
          {{- end }}
        resources:
          {{- toYaml .Values.traction_adapter.resources | nindent 12 }}
      serviceAccountName: {{ if .Values.traction_adapter.serviceAccount.create }}{{ if .Values.traction_adapter.serviceAccount.name }}{{ .Values.traction_adapter.serviceAccount.name }}{{ else }}{{ $.Release.Name }}-{{ .Values.traction_adapter.name }}{{ end }}{{ end }}
{{- end }}