apiVersion: v1
kind: Service
metadata:
  name: {{ include "showcase.web.fullname" . }}
  namespace: {{ include "showcase.namespace" . | quote }}
  labels: {{- include "showcase.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  type: ClusterIP
  selector:
    {{- include "showcase.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web
  ports:
    - name: http
      port: {{ .Values.showcase.web.containerPort }}
      targetPort: http
