import DOMPurify from 'isomorphic-dompurify'

/**
 * Sanitize SVG content by removing potentially dangerous elements and attributes
 * Uses DOMPurify which is a well-maintained, industry-standard HTML/SVG sanitizer
 */
export function sanitizeSVG(content: string): string {
  // Configure DOMPurify for SVG content
  const config = {
    ALLOWED_TAGS: [
      'svg',
      'g',
      'path',
      'rect',
      'circle',
      'ellipse',
      'line',
      'polyline',
      'polygon',
      'text',
      'tspan',
      'image',
      'use',
      'symbol',
      'defs',
      'linearGradient',
      'radialGradient',
      'stop',
      'marker',
      'pattern',
      'mask',
      'clipPath',
      'title',
      'desc',
      'metadata',
      'foreignObject',
      'style',
      'a',
    ],
    ALLOWED_ATTR: [
      'viewBox',
      'width',
      'height',
      'xmlns',
      'xmlns:xlink',
      'xlink:href',
      'x',
      'y',
      'cx',
      'cy',
      'r',
      'rx',
      'ry',
      'x1',
      'y1',
      'x2',
      'y2',
      'd',
      'fill',
      'stroke',
      'stroke-width',
      'stroke-linecap',
      'stroke-linejoin',
      'opacity',
      'transform',
      'id',
      'class',
      'style',
      'points',
      'offset',
      'stop-color',
      'stop-opacity',
      'gradientUnits',
      'gradientTransform',
      'fx',
      'fy',
      'spreadMethod',
      'href',
      'preserveAspectRatio',
      'viewBox',
      'refX',
      'refY',
      'markerWidth',
      'markerHeight',
      'markerUnits',
      'orient',
      'patternUnits',
      'patternTransform',
      'maskUnits',
      'clipPathUnits',
      'font-family',
      'font-size',
      'text-anchor',
      'dominant-baseline',
      'paint-order',
      'fill-rule',
      'clip-rule',
      'stroke-dasharray',
      'stroke-dashoffset',
      'stroke-miterlimit',
    ],
    KEEP_CONTENT: true,
  }

  return DOMPurify.sanitize(content, config)
}
