apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bc-wallet.fullname" . }}-api-server
  labels:
    app.kubernetes.io/component: api-server
    {{- include "bc-wallet.labels" . | nindent 4 }}
spec:
  {{- if not .Values.apiServer.autoscaling.enabled }}
  replicas: {{ .Values.apiServer.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: api-server
      {{- include "bc-wallet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.apiServer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: api-server
        {{- include "bc-wallet.labels" . | nindent 8 }}
        {{- with .Values.apiServer.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.apiServer.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bc-wallet.serviceAccountName" . }}
      {{- with .Values.apiServer.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        - name: wait-for-postgres
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ .Release.Name }}-postgresql {{ .Values.postgresql.primary.service.ports.postgresql | quote }}; do echo waiting for postgres; sleep 2; done; sleep 2;']
        - name: wait-for-rabbitmq
          image: busybox
          command: ['sh', '-c', 'until nc -z {{ .Release.Name }}-rabbitmq {{ .Values.rabbitmq.service.ports.amqp | quote }}; do echo waiting for rabbitmq; sleep 2; done; sleep 5;']
      containers:
        - name: api-server
          {{- with .Values.apiServer.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.apiServer.image.repository }}:{{ .Values.apiServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apiServer.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.apiServer.service.port }}
              protocol: TCP
          env:
            - name: AMQ_HOST
              value: {{.Release.Name}}-rabbitmq
            - name: AMQ_PORT
              value: {{ .Values.rabbitmq.service.ports.amqp | quote }}
            - name: AMQ_TRANSPORT
              value: tcp
            - name: AMQ_USERNAME
              value: {{ .Values.rabbitmq.auth.username | quote }}
            - name: AMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "bc-wallet.rabbitmq.secret.name" . }}
                  key: {{ include "bc-wallet.rabbitmq.passwordKey" . }}
            - name: SHOWCASE_DB_PORT
              value: {{ .Values.postgresql.primary.service.ports.postgresql | quote }}
            - name: SHOWCASE_DB_USERNAME
              value: {{ .Values.postgresql.auth.username | quote }}
            - name: SHOWCASE_DB_NAME
              value: {{ .Values.postgresql.auth.database | quote }}
            - name: SHOWCASE_DB_HOST
              value: {{ .Release.Name }}-postgresql
            - name: SHOWCASE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "bc-wallet.database.secret.name" . }}
                  key: {{ include "bc-wallet.database.userPasswordKey" . }}
            - name: CORS_ALLOW_ORIGINS
              value: "https://{{ include "bc-wallet.showcaseCreator.host" . }},https://{{ include "bc-wallet.demoWeb.host" . }}"
            - name: OIDC_ROOT_CLIENT_ID
               valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiServer.secretName | default "bc-wallet-secrets" | quote }}
                  key: OIDC_ROOT_CLIENT_ID
            - name: OIDC_ROOT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiServer.secretName | default "bc-wallet-secrets" | quote }}
                  key: OIDC_ROOT_CLIENT_SECRET
            - name: OIDC_ROOT_ISSUER_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiServer.secretName | default "bc-wallet-secrets" | quote }}
                  key: OIDC_ROOT_ISSUER_URL
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.apiServer.secretName | default "bc-wallet-secrets" | quote }}
                  key: ENCRYPTION_KEY
          {{- with .Values.apiServer.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apiServer.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apiServer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apiServer.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.apiServer.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiServer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiServer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiServer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
