{{- if and .Values.api_server.serviceAccount (eq .Values.api_server.serviceAccount.create true) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ if .Values.api_server.serviceAccount.name }}{{ .Values.api_server.serviceAccount.name }}{{ else }}{{ include "bc-wallet-showcase-builder.fullname" . }}-api-server{{ end }}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: bc-wallet
    {{- include "bc-wallet-showcase-builder.labels" . | nindent 4 }}
  {{- with .Values.api_server.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}