{{- if .Values.ui.enabled }}
{{- $authtokenSecretName := include "credential-showcase.authtoken.secret.name" . -}}
{{- $authtokenSecret := (lookup "v1" "Secret" .Release.Namespace $authtokenSecretName) -}}
{{- if not $authtokenSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "credential-showcase.authtoken.secret.name" . }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ .Release.Name }}-{{ .Values.ui.name }}
type: Opaque
data:
  token: {{ include "getOrGeneratePass" (dict "Kind" "Secret" "Namespace" .Release.Namespace "Name" (include "credential-showcase.authtoken.secret.name" .) "Key" "token" "Length" 32) }}
{{- end }}
{{- end }} 