{{- if and .Values.ingress.enabled (not .Values.ui.openshift.route.enabled) }}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-ui-route
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ (index .Values.ingress.hosts 0).host }}`)
      kind: Rule
      services:
        - name: {{ .Release.Name }}-{{ .Values.ui.name }}
          namespace: {{ .Release.Namespace }}
          port: {{ .Values.ui.service.port }}
      middlewares:
        - name: redirect-https
          namespace: kube-system
  tls:
    secretName: showcase-tls
{{- end }} 