{{- if .Values.ui.enabled }}
{{- if .Values.ui.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-{{ .Values.ui.name }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.ui.name }}
  policyTypes:
    - Ingress
  ingress:
    {{- if .Values.ui.networkPolicy.ingress.enabled }}
    - from:
        {{- with .Values.ui.networkPolicy.ingress.namespaceSelector }}
        - namespaceSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.ui.networkPolicy.ingress.podSelector }}
        - podSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
    {{- end }}
{{- end }}
{{- end }} 