{{- if .Values.ui.enabled }}
{{- if .Values.ui.openshift.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Release.Name }}-{{ .Values.ui.name }}
spec:
  host: pr-{{ .Release.Name }}-{{ .Values.ui.name }}-dev.apps.silver.devops.gov.bc.ca
  path: {{ .Values.ui.openshift.route.path }}
  port:
    targetPort: {{ .Values.ui.openshift.route.targetPort }}
  tls:
    {{- toYaml .Values.ui.openshift.route.tls | nindent 4 }}
  to:
    kind: Service
    name: {{ .Release.Name }}-{{ .Values.ui.name }}
  wildcardPolicy: None
{{- end }}
{{- end }} 