{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.ui.name }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: {{ .Values.ui.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-{{ .Values.ui.name }}
{{- end }} 