name: Build Docker Image
inputs:
  ref:
    description: 'The branch, tag or SHA to checkout'
    required: false
    default: ''  
  context:
    required: true
    type: string
    default: '.'
  dockerfile:
    required: true
    type: string
  image_name:
    required: true
    type: string
  registry:
    required: true
    type: string
    default: ghcr.io
  registry_username:
    required: true
    type: string
  registry_password:
    required: true

outputs:
  image_tag:
    description: "Image Tag"
    value: ${{ steps.values.outputs.image_tag }}

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4   
      with:
        ref: ${{ inputs.ref != '' && inputs.ref || env.GITHUB_REF }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry}}
        username: ${{ inputs.registry_username}}
        password: ${{ inputs.registry_password }}

    - name: Prepare docker tags for image
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ inputs.image_name }}
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=ref,event=pr
          type=sha

    - name: Build and push image
      id: builder
      uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    - id: values  
      shell: bash
      run: |
        echo "image_tag=${{ fromJSON(steps.meta.outputs.json).tags[0] }}" >> $GITHUB_OUTPUT
