nameOverride: ""
fullnameOverride: ""

ui:
  name: showcase-ui
  image:
    repository: public.ecr.aws/k8o4d9r5/bcshowcase/ditp-showcase-creator-ui
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: "0.1-alpha"
  replicaCount: 1
  port: 3050
  path: /
  env:
    NODE_ENV: development
    API_URL: "https://bcshowcase-api.dev.nborbit.ca/"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  service:
    type: ClusterIP
    port: 3050
  affinity: {}
  nodeSelector: {}
  tolerations: []
  networkPolicy:
    enabled: false
    ingress:
      enabled: false
      namespaceSelector: {}
      podSelector: {}
  openshift:
    route:
      enabled: false
      path: "/"
      targetPort: http
      tls:
        enabled: true
        termination: edge
  enabled: true
  serviceAccount:
    create: false
    name: ""
    annotations: {}
    automountServiceAccountToken: true
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "traefik"
      traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
      traefik.ingress.kubernetes.io/router.tls: "true"
    host: "bcshowcase-ui.dev.nborbit.ca"

# Global ingress settings
ingress:
  enabled: true
  className: "traefik"
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: bcshowcase-ui.dev.nborbit.ca
      paths:
        - path: /
          pathType: Prefix
          service: ui
  tls:
    - secretName: showcase-ui-tls
      hosts:
        - bcshowcase-ui.dev.nborbit.ca

debug: true 