name: 'Build Docker Image'
description: 'Builds and pushes a Docker image to a registry'
inputs:
  context:
    description: 'Docker build context'
    required: true
  dockerfile:
    description: 'Path to Dockerfile'
    required: true
  image_name:
    description: 'Name of the image'
    required: true
  registry:
    description: 'Container registry'
    required: true
  registry_username:
    description: 'Registry username'
    required: true
  registry_password:
    description: 'Registry password'
    required: true
  visibility:
    description: 'Package visibility (public or private)'
    required: false
    default: 'private'
outputs:
  image_tag:
    description: 'The tag of the built image'
    value: ${{ steps.docker_build.outputs.image_tag }}
runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.registry_username }}
        password: ${{ inputs.registry_password }}

    - name: Generate image tag
      id: docker_build
      shell: bash
      run: |
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          TAG="pr-${{ github.event.number }}"
        else
          TAG="${{ github.sha }}"
        fi
        echo "image_tag=${TAG}" >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ steps.docker_build.outputs.image_tag }}

    - name: Set package visibility
      if: inputs.registry == 'ghcr.io' && inputs.visibility == 'public'
      shell: bash
      run: |
        # Get the package name from the image name
        PACKAGE_NAME=$(echo "${{ inputs.image_name }}" | tr '/' '_')
        
        # Use GitHub API to set package visibility to public
        curl -X PATCH \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ inputs.registry_password }}" \
          -d '{"visibility":"public"}' \
          "https://api.github.com/user/packages/container/$PACKAGE_NAME"