apiVersion: v2
name: bc-wallet
description: BC Wallet Showcase Builder services with PostgreSQL and RabbitMQ
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: postgresql
    version: "16.6.3"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: rabbitmq
    version: "15.5.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled
