nameOverride: ""
fullnameOverride: ""

global:
  namespaceOverride: ""

# Add ingressSuffix for dynamic host generation
ingressSuffix: "-dev.apps.silver.devops.gov.bc.ca"

ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: openshift-default
    route.openshift.io/termination: edge
  hosts:
    - host: ""  
      paths:
        - path: /
          pathType: Prefix
          service: api-server
    - host: ""  
      paths:
        - path: /
          pathType: Prefix
          service: traction-adapter
    - host: ""  
      paths:
        - path: /
          pathType: Prefix
          service: demo-web
    - host: "" 
      paths:
        - path: /
          pathType: Prefix
          service: showcase-creator
    - host: "" 
      paths:
        - path: /
          pathType: Prefix
          service: demo-server
  tls: []

api_server:
  image:
    repository: ghcr.io/bcgov/bc-wallet-api-server
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: "latest"
  replicaCount: 1
  labelOverride: ""
  port: 3000
  path: /
  env:
    LOG_LEVEL: debug
    CORS_DISABLED: true
    CORS_ALLOW_METHODS: "GET, POST, PUT, DELETE, OPTIONS"
    CORS_ALLOW_HEADERS: "Content-Type, Authorization"
    CORS_ALLOW_CREDENTIALS: "true"
    OIDC_REALM: your_oidc_realm
    OIDC_SERVER_URL: your_oidc_server_url
    ENCRYPTION_KEY: SENSITIVE
    OIDC_CLIENT_ID: SENSITIVE
    OIDC_CLIENT_SECRET: SENSITIVE
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  service:
    type: ClusterIP
    port: 3000
  affinity: {}
  nodeSelector: {}
  tolerations: []
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector: 
        network.openshift.io/policy-group: ingress
      podSelector: {}
  enabled: true
  serviceAccount:
    create: false
    name: ""
    annotations: {}
    automountServiceAccountToken: true
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300

traction_adapter:
  image:
    repository: ghcr.io/bcgov/bc-wallet-traction-adapter
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: "latest"
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300
  labelOverride: ""
  port: 3000
  path: /traction
  env:
    APP_NAME: bc-wallet-traction-adapter
    PORT: 3000
    LOG_LEVEL: debug
    TRACTION_DEFAULT_TENANT_ID: "your_tenant_id"
    TRACTION_DEFAULT_WALLET_ID: "your_wallet_id"
    TRACTION_DEFAULT_API_URL: "https://traction-sandbox-tenant-proxy.apps.silver.devops.gov.bc.ca"
    TRACTION_DEFAULT_API_KEY: SENSITIVE
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  service:
    type: ClusterIP
    port: 3000
  affinity: {}
  nodeSelector: {}
  tolerations: []
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector: 
        network.openshift.io/policy-group: ingress
      podSelector: {}
  enabled: true
  serviceAccount:
    create: false
    annotations: {}
    automountServiceAccountToken: true
    name: ""

demo_web:
  image:
    repository: ghcr.io/bcgov/bc-wallet-demo-web
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: "latest"
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300
  labelOverride: ""
  port: 3000
  path: /
  env:
    NODE_ENV: production
    LOG_LEVEL: debug
    REACT_APP_BASE_ROUTE: /digital-trust/showcase
    DEMOWEB_SNOWPLOW_ENDPOINT: "spm.apps.gov.bc.ca"
    REACT_APP_INSIGHTS_PROJECT_ID: your_insights_project_id
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  service:
    type: ClusterIP
    port: 3000
  affinity: {}
  nodeSelector: {}
  tolerations: []
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector: 
        network.openshift.io/policy-group: ingress
      podSelector: {}
  enabled: true
  serviceAccount:
    create: false
    annotations: {}
    automountServiceAccountToken: true
    name: ""

showcase_creator:
  image:
    repository: ghcr.io/bcgov/bc-wallet-showcase-creator
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: "latest"
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300
  labelOverride: ""
  port: 3050
  path: /
  env:
    NODE_ENV: production
    PORT: 3050
    OIDC_ISSUER_URL: your_oidc_issuer_url # ADD KEYCLOAK ISSUER HERE
    OIDC_TRUST_HOST: "true"
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  service:
    type: ClusterIP
    port: 3050
  affinity: {}
  nodeSelector: {}
  tolerations: []
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector: 
        network.openshift.io/policy-group: ingress
      podSelector: {}
  enabled: true
  serviceAccount:
    create: false
    annotations: {}
    automountServiceAccountToken: true
    name: ""

demo_server:
  image:
    repository: ghcr.io/bcgov/bc-wallet-demo-server
    pullPolicy: IfNotPresent
    pullSecrets: []
    tag: "latest"
  replicaCount: 1
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    stabilizationWindowSeconds: 300
  labelOverride: ""
  port: 3000
  path: /
  env:
    LOG_LEVEL: debug
    CORS_DISABLED: true
    CORS_ALLOW_METHODS: "GET, POST, PUT, DELETE, OPTIONS"
    CORS_ALLOW_HEADERS: "Content-Type, Authorization"
    CORS_ALLOW_CREDENTIALS: "true"
    TRACTION_WEBHOOK_SECRET: SENSITIVE
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}
  service:
    type: ClusterIP
    port: 3000
  affinity: {}
  nodeSelector: {}
  tolerations: []
  networkPolicy:
    enabled: true
    ingress:
      enabled: true
      namespaceSelector: 
        network.openshift.io/policy-group: ingress
      podSelector: {}
  enabled: true
  serviceAccount:
    create: false
    annotations: {}
    automountServiceAccountToken: true
    name: ""

postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    username: "showcase-user"
    database: "showcase-db"
    secretKeys:
      adminPasswordKey: "postgres-password"
      userPasswordKey: "password"
  primary:
    service:
      ports:
        postgresql: 5432
    persistence:
      enabled: true
      size: 1Gi
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    podSecurityContext:
      enabled: false
    containerSecurityContext:
      enabled: false
  networkPolicy:
    enabled: true
  fullnameOverride: ""

rabbitmq:
  enabled: true
  auth:
    username: "bc_user"
    password: "some_password"
    existingSecret: ""
    existingSecretKey: "rabbitmq-password"
    erlangCookie: ""
    existingErlangSecret: ""
    existingErlangSecretKey: "rabbitmq-erlang-cookie"
  extraPlugins: "rabbitmq_management rabbitmq_amqp1_0"
  configuration: |-
    management.listener.port = 15672
    management.listener.ssl = false
    default_user = bc_user
    default_pass = some_password
  extraConfiguration: |-
    default_user = bc_user
    default_pass = some_password
  service:
    type: ClusterIP
    ports:
      amqp: 5672
      manager: 15672
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  persistence:
    enabled: true
    size: 1Gi
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  containerSecurityContext:
    enabled: false
  podSecurityContext:
    enabled: false
  replicaCount: 1
  pdb:
    create: true
    minAvailable: 1
  networkPolicy:
    enabled: true
  fullnameOverride: ""