apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bc-wallet.fullname" . }}-showcase-creator
  labels:
    app.kubernetes.io/component: showcase-creator
    {{- include "bc-wallet.labels" . | nindent 4 }}
spec:
  {{- if not .Values.showcaseCreator.autoscaling.enabled }}
  replicas: {{ .Values.showcaseCreator.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/component: showcase-creator
      {{- include "bc-wallet.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.showcaseCreator.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: showcase-creator
        {{- include "bc-wallet.labels" . | nindent 8 }}
        {{- with .Values.showcaseCreator.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.showcaseCreator.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bc-wallet.serviceAccountName" . }}
      {{- with .Values.showcaseCreator.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: showcase-creator
          {{- with .Values.showcaseCreator.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.showcaseCreator.image.repository }}:{{ .Values.showcaseCreator.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.showcaseCreator.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.showcaseCreator.service.port }}
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_WALLET_URL
              value: "https://{{ include "bc-wallet.demoWeb.host" . }}/digital-trust/showcase"
            - name: NEXT_PUBLIC_SHOWCASE_API_URL
              value: "https://{{ include "bc-wallet.apiServer.host" . }}"
            - name: OIDC_REDIRECT_PROXY_URL
              value: "https://{{ include "bc-wallet.showcaseCreator.host" . }}/api/auth"
            - name: OIDC_AUTH_URL
              value: "https://{{ include "bc-wallet.showcaseCreator.host" . }}"
            - name: NODE_ENV
              value: production
            - name: PORT
              value: {{ .Values.showcaseCreator.service.port | quote }}
          {{- if or .Values.showcaseCreator.extraEnvVarsCM .Values.showcaseCreator.extraEnvVarsSecret }}
          envFrom:
            {{- if .Values.showcaseCreator.extraEnvVarsCM }}
            - configMapRef:
                name: {{ .Values.showcaseCreator.extraEnvVarsCM | quote }}
            {{- end }}
            {{- if .Values.showcaseCreator.extraEnvVarsSecret }}
            - secretRef:
                name: {{ .Values.showcaseCreator.extraEnvVarsSecret | quote }}
            {{- end }}
          {{- end }}
          {{- with .Values.showcaseCreator.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.showcaseCreator.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.showcaseCreator.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.showcaseCreator.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.showcaseCreator.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.showcaseCreator.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.showcaseCreator.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.showcaseCreator.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
