{{- if .Values.showcase_creator.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.showcase_creator.name }}
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.showcase_creator.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.showcase_creator.labelOverride }}
    app.kubernetes.io/component: {{ .Values.showcase_creator.labelOverride }}
    {{- else }}
    app.kubernetes.io/component: showcase-creator
    {{- end }}
spec:
  type: {{ .Values.showcase_creator.service.type }}
  ports:
    - port: {{ .Values.showcase_creator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Release.Name }}-{{ .Values.showcase_creator.name }}
{{- end }} 