{{- if .Values.demo_server.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bc-wallet.fullname" . }}-demo-server
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: bc-wallet
    {{- include "bc-wallet.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.demo_server.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "bc-wallet.fullname" . }}-demo-server
  template:
    metadata:
      labels:
        app: {{ include "bc-wallet.fullname" . }}-demo-server
        app.kubernetes.io/component: server
        app.kubernetes.io/part-of: bc-wallet
        {{- include "bc-wallet.labels" . | nindent 8 }}
      {{- with .Values.demo_server.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.demo_server.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: demo-server
        image: "{{ .Values.demo_server.image.repository }}:{{ .Values.demo_server.image.tag }}"
        imagePullPolicy: {{ .Values.demo_server.image.pullPolicy }}
        {{- with .Values.demo_server.containerSecurityContext }}
        securityContext:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.demo_server.port }}
          name: http
        env:
        - name: CORS_ALLOW_ORIGINS
          value: "https://{{ include "bc-wallet.showcase-creator.host" . }},https://{{ include "bc-wallet.demo-web.host" . }}"
        - name: SHOWCASE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "bc-wallet.database.secret.name" . }}
              key: {{ include "bc-wallet.database.userPasswordKey" . }}
        - name: API_KEY
          value: {{ .Values.traction_adapter.env.TRACTION_DEFAULT_API_KEY | quote }}
        - name: TENANT_ID
          value: {{ .Values.traction_adapter.env.TRACTION_DEFAULT_TENANT_ID | quote }}
        - name: WALLET_ID
          value: {{ .Values.traction_adapter.env.TRACTION_DEFAULT_WALLET_ID | quote }}
        - name: TRACTION_API_URL
          value: {{ .Values.traction_adapter.env.TRACTION_API_URL | quote }}
        - name: BASE_ROUTE
          value: {{ .Values.demo_web.env.REACT_APP_BASE_ROUTE | quote }}
        resources:
          {{- toYaml .Values.demo_server.resources | nindent 12 }}
      serviceAccountName: {{ if .Values.demo_server.serviceAccount.create }}{{ if .Values.demo_server.serviceAccount.name }}{{ .Values.demo_server.serviceAccount.name }}{{ else }}{{ include "bc-wallet.fullname" . }}-demo-server{{ end }}{{ end }}
{{- end }} 