{{- if and .Values.demo_server.enabled .Values.demo_server.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "bc-wallet-showcase-builder.fullname" . }}-demo-server-allow-external
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: bc-wallet
    {{- include "bc-wallet-showcase-builder.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "bc-wallet-showcase-builder.fullname" . }}-demo-server
  ingress:
  - from:
    {{- if .Values.demo_server.networkPolicy.ingress.namespaceSelector }}
    - namespaceSelector:
        matchLabels:
          {{- if kindIs "map" .Values.demo_server.networkPolicy.ingress.namespaceSelector }}
          {{- toYaml .Values.demo_server.networkPolicy.ingress.namespaceSelector | nindent 10 }}
          {{- end }}
      {{- if .Values.demo_server.networkPolicy.ingress.podSelector }}
      podSelector:
        {{- toYaml .Values.demo_server.networkPolicy.ingress.podSelector | nindent 10 }}
      {{- end }}
    {{- else }}
    - {}  # Allow all ingress traffic if no selector specified
    {{- end }}
---
# Network policy for Demo Server to database
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Release.Name }}-postgres-allow-demo-server
  namespace: {{ .Values.global.namespaceOverride | default .Release.Namespace }}
  labels:
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: bc-wallet
    {{- include "bc-wallet-showcase-builder.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: {{ .Release.Name }}
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ include "bc-wallet-showcase-builder.fullname" . }}-demo-server
    ports:
    - protocol: TCP
      port: {{ .Values.postgresql.primary.service.ports.postgresql }}
---
{{- $context := dict "componentName" "demo-server" "componentLabel" "server" "servicePort" .Values.demo_server.service.port "Values" .Values "Release" .Release }}
{{- include "bc-wallet-showcase-builder.intra-release-network-policy" $context }}
{{- end }} 