name: Build, Push and Deploy 
on:
  workflow_dispatch:
  push:
    branches:
      # - main
      - showcase-builder
    paths:
        - "apps/bc-wallet-api-server/**"
        - "apps/bc-wallet-traction-adapter/**"
        - "apps/bc-wallet-showcase-creator/**"
        - "apps/bc-wallet-demo-server/**"
        - "apps/bc-wallet-demo-web/**"
        - "charts/**"
        - ".github/**"

jobs:
  build_api_server:
    name: "Build API Server"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Build API Server Image
        uses: ./.github/actions/build_docker
        id: builder
        with:
          context: "."
          dockerfile: "./apps/bc-wallet-api-server/Dockerfile"
          image_name: ${{ github.repository_owner}}/bc-wallet-api-server
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner}}/bc-wallet-api-server:${{ steps.builder.outputs.image_tag }}
          format: 'sarif'
          output: 'trivy-bc-wallet-api-server.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-bc-wallet-api-server.sarif'
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}

  build_traction_adapter:
    name: "Build Traction Adapter"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Build Traction Adapter Image
        uses: ./.github/actions/build_docker
        id: builder
        with:
          context: "."
          dockerfile: "./apps/bc-wallet-traction-adapter/Dockerfile"
          image_name: ${{ github.repository_owner}}/bc-wallet-traction-adapter
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner}}/bc-wallet-traction-adapter:${{ steps.builder.outputs.image_tag }}
          format: 'sarif'
          output: 'trivy-bc-wallet-traction-adapter.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-bc-wallet-traction-adapter.sarif'
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}

  build_showcase_creator:
    name: "Build Showcase Creator"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Build Showcase Creator Image
        uses: ./.github/actions/build_docker
        id: builder
        with:
          context: "."
          dockerfile: "./apps/bc-wallet-showcase-creator/Dockerfile"
          image_name: ${{ github.repository_owner}}/bc-wallet-showcase-creator
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner}}/bc-wallet-showcase-creator:${{ steps.builder.outputs.image_tag }}
          format: 'sarif'
          output: 'trivy-bc-wallet-showcase-creator.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-bc-wallet-showcase-creator.sarif'
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}

  build_demo_server:
    name: "Build Demo Server"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Build Demo Server Image
        uses: ./.github/actions/build_docker
        id: builder
        with:
          context: "."
          dockerfile: "./apps/bc-wallet-demo-server/Dockerfile"
          image_name: ${{ github.repository_owner}}/bc-wallet-demo-server
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner}}/bc-wallet-demo-server:${{ steps.builder.outputs.image_tag }}
          format: 'sarif'
          output: 'trivy-bc-wallet-demo-server.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-bc-wallet-demo-server.sarif'
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}

  build_demo_web:
    name: "Build Demo Web"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Build Demo Web Image
        uses: ./.github/actions/build_docker
        id: builder
        with:
          context: "."
          dockerfile: "./apps/bc-wallet-demo-web/Dockerfile"
          image_name: ${{ github.repository_owner}}/bc-wallet-demo-web
          registry: ghcr.io
          registry_username: ${{ github.repository_owner}}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ghcr.io/${{ github.repository_owner}}/bc-wallet-demo-web:${{ steps.builder.outputs.image_tag }}
          format: 'sarif'
          output: 'trivy-bc-wallet-demo-web.sarif'
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-bc-wallet-demo-web.sarif'
    outputs:
      image_tag: ${{ steps.builder.outputs.image_tag }}

  deploy_dev:
    name: Deploy to Development
    environment: development
    runs-on: ubuntu-latest
    needs:
      - build_api_server
      - build_traction_adapter
      - build_showcase_creator
      - build_demo_server
      - build_demo_web
    if: ${{ contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.14"
 
      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}
          namespace: ${{ secrets.OPENSHIFT_DEV_NAMESPACE }}
     
      - name: Deploy to OpenShift with Helm
        run: |
          cd charts/bc-wallet
          helm upgrade --install bc-wallet-demo --namespace ${{ vars.OPENSHIFT_NAMESPACE }} -f ./values.yaml \
            --set apiServer.image.tag=${{ needs.build_api_server.outputs.image_tag }} \
            --set tractionAdapter.image.tag=${{ needs.build_traction_adapter.outputs.image_tag }} \
            --set showcaseCreator.image.tag=${{ needs.build_showcase_creator.outputs.image_tag }} \
            --set demoWeb.image.tag=${{ needs.build_demo_web.outputs.image_tag }} \
            --set demoServer.image.tag=${{ needs.build_demo_server.outputs.image_tag }} \
            . --wait
      
      - name: Restart Deployments
        run: |
          oc rollout restart deployment/bc-wallet-demo-api-server
          oc rollout restart deployment/bc-wallet-demo-traction-adapter
          oc rollout restart deployment/bc-wallet-demo-showcase-creator
          oc rollout restart deployment/bc-wallet-demo-demo-server
          oc rollout restart deployment/bc-wallet-demo-demo-web

  deploy_uat:
    name: Deploy to UAT
    environment: uat  
    runs-on: ubuntu-latest
    needs: deploy_dev
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.14"

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}
          namespace: ${{ secrets.OPENSHIFT_UAT_NAMESPACE }}
     
      - name: Deploy to OpenShift with Helm
        run: |
          cd charts/bc-wallet
          helm upgrade --install bc-wallet-demo --namespace ${{ vars.OPENSHIFT_NAMESPACE }} -f ./values.yaml \
            --set apiServer.image.tag=${{ needs.build_api_server.outputs.image_tag }} \
            --set tractionAdapter.image.tag=${{ needs.build_traction_adapter.outputs.image_tag }} \
            --set showcaseCreator.image.tag=${{ needs.build_showcase_creator.outputs.image_tag }} \
            --set demoWeb.image.tag=${{ needs.build_demo_web.outputs.image_tag }} \
            --set demoServer.image.tag=${{ needs.build_demo_server.outputs.image_tag }} \
            . --wait
      
      - name: Restart Deployments
        run: |
          oc rollout restart deployment/bc-wallet-demo-api-server
          oc rollout restart deployment/bc-wallet-demo-traction-adapter
          oc rollout restart deployment/bc-wallet-demo-showcase-creator
          oc rollout restart deployment/bc-wallet-demo-demo-server
          oc rollout restart deployment/bc-wallet-demo-demo-web

  deploy_prod:
    name: Deploy to Production
    environment: production 
    runs-on: ubuntu-latest
    needs: deploy_uat
    steps:
      - uses: actions/checkout@v4

      - name: Install OpenShift CLI tools
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: "4.14"

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          certificate_authority_data: ${{ secrets.OPENSHIFT_CA_CRT }}
          namespace: ${{ secrets.OPENSHIFT_PROD_NAMESPACE }}
     
      - name: Deploy to OpenShift with Helm
        run: |
          cd charts/bc-wallet
          helm upgrade --install bc-wallet-demo --namespace ${{ vars.OPENSHIFT_NAMESPACE }} -f ./values.yaml \
            --set apiServer.image.tag=${{ needs.build_api_server.outputs.image_tag }} \
            --set tractionAdapter.image.tag=${{ needs.build_traction_adapter.outputs.image_tag }} \
            --set showcaseCreator.image.tag=${{ needs.build_showcase_creator.outputs.image_tag }} \
            --set demoWeb.image.tag=${{ needs.build_demo_web.outputs.image_tag }} \
            --set demoServer.image.tag=${{ needs.build_demo_server.outputs.image_tag }} \
            . --wait
      
      - name: Restart Deployments
        run: |
          oc rollout restart deployment/bc-wallet-demo-api-server
          oc rollout restart deployment/bc-wallet-demo-traction-adapter
          oc rollout restart deployment/bc-wallet-demo-showcase-creator
          oc rollout restart deployment/bc-wallet-demo-demo-server
          oc rollout restart deployment/bc-wallet-demo-demo-web

  image-scan:
    name: "Image Scan"
    needs:
      - build_api_server
      - build_traction_adapter
      - build_showcase_creator
      - build_demo_server
      - build_demo_web
    runs-on: ubuntu-latest
    steps:
      - name: Run Trivy Image Scan
        uses: ./.github/actions/trivy-scan
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/bc-wallet-api-server:${{ needs.build_api_server.outputs.image_tag }},
            ghcr.io/${{ github.repository_owner }}/bc-wallet-traction-adapter:${{ needs.build_traction_adapter.outputs.image_tag }},
            ghcr.io/${{ github.repository_owner }}/bc-wallet-demo-web:${{ needs.build_demo_web.outputs.image_tag }},
            ghcr.io/${{ github.repository_owner }}/bc-wallet-showcase-creator:${{ needs.build_showcase_creator.outputs.image_tag }},
            ghcr.io/${{ github.repository_owner }}/bc-wallet-demo-server:${{ needs.build_demo_server.outputs.image_tag }}
