name: Uninstall PR resources
on:
  # Add manual trigger with PR number input
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to uninstall'
        required: true
        type: string
  pull_request:
    branches:
      - random-branch # change this to main or your branch
      # - main
      # - develop-4sure
    paths:
      - "apps/bc-wallet-api-server/**"
      - "packages/bc-wallet-traction-adapter/**"
      - "apps/bc-wallet-showcase-creator/**"
      - "apps/bc-wallet-demo-server/**"
      - "apps/bc-wallet-demo-web/**"
      - "charts/**"
    types:
      - closed

jobs:
  ready:
    name: "Check if PR is ready for review"
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.ready_for_review.outputs.true_false }}
      build: ${{ steps.ready_for_review.outputs.owner_true_false }}
    steps:
      - id: ready_for_review
        run: |
          echo "true_false=${{ toJSON(github.event.pull_request.draft != true && github.repository_owner == '4sure-tech') }}" >> $GITHUB_OUTPUT
          echo "owner_true_false=${{ toJSON(github.repository_owner == '4sure-tech') }}" >> $GITHUB_OUTPUT

  uninstall:
    name: Uninstall PR Resources
    environment: development
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      # Set PR number based on event type
      - name: Set PR number
        id: pr_number
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "PR_NUM=${{ github.event.inputs.pr_number }}" >> $GITHUB_ENV
          else
            echo "PR_NUM=${{ github.event.number }}" >> $GITHUB_ENV
          fi

      # Uninstall resources via SSH to K3s server
      - name: Uninstall resources from K3s
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.K3S_HOST }}
          username: ${{ secrets.K3S_USERNAME }}
          key: ${{ secrets.K3S_SSH_KEY }}
          script: |
            # Uninstall Helm release
            helm uninstall pr-${{ env.PR_NUM }}-bc-wallet || true
            
            # Delete any remaining resources
            kubectl delete secret,pvc,service,deployment,statefulset,configmap,ingress,ingressroute,certificate \
              --selector "app.kubernetes.io/instance=pr-${{ env.PR_NUM }}-bc-wallet" || true
            
            # Delete IngressRoutes specifically
            kubectl delete ingressroute \
              api-server-route-pr-${{ env.PR_NUM }} \
              traction-adapter-route-pr-${{ env.PR_NUM }} \
              showcase-creator-route-pr-${{ env.PR_NUM }} \
              demo-web-route-pr-${{ env.PR_NUM }} \
              demo-server-route-pr-${{ env.PR_NUM }} || true
            
            # Delete Certificate
            kubectl delete certificate bc-wallet-tls-pr-${{ env.PR_NUM }} || true

  clean-ghcr:
    runs-on: ubuntu-latest
    name: Delete closed PR images
    steps:
      - name: Delete API Server Image
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          image-names: bc-wallet-api-server
          image-tags: ${{ github.event.number != '' && format('pr-{0}', github.event.number) || format('pr-{0}', github.event.inputs.pr_number) }}
          cut-off: 1second
          token: ${{ secrets.CR_PAT }}
          
      - name: Delete Traction Adapter Image
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          image-names: bc-wallet-traction-adapter
          image-tags: ${{ github.event.number != '' && format('pr-{0}', github.event.number) || format('pr-{0}', github.event.inputs.pr_number) }}
          cut-off: 1second
          token: ${{ secrets.CR_PAT }}

      - name: Delete Showcase Creator Image
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          image-names: bc-wallet-showcase-creator 
          image-tags: ${{ github.event.number != '' && format('pr-{0}', github.event.number) || format('pr-{0}', github.event.inputs.pr_number) }}
          cut-off: 1second
          token: ${{ secrets.CR_PAT }}

      - name: Delete Demo Server Image
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          image-names: bc-wallet-demo-server 
          image-tags: ${{ github.event.number != '' && format('pr-{0}', github.event.number) || format('pr-{0}', github.event.inputs.pr_number) }}
          cut-off: 1second
          token: ${{ secrets.CR_PAT }}

      - name: Delete Demo Web Image
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          image-names: bc-wallet-demo-web 
          image-tags: ${{ github.event.number != '' && format('pr-{0}', github.event.number) || format('pr-{0}', github.event.inputs.pr_number) }}
          cut-off: 1second
          token: ${{ secrets.CR_PAT }}